# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/anna/Документы/kur

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/anna/Документы/kur

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/anna/Документы/kur/CMakeFiles /home/anna/Документы/kur//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/anna/Документы/kur/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sfmlapp

# Build rule for target.
sfmlapp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfmlapp
.PHONY : sfmlapp

# fast build rule for target.
sfmlapp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfmlapp.dir/build.make CMakeFiles/sfmlapp.dir/build
.PHONY : sfmlapp/fast

Engine.o: Engine.cpp.o
.PHONY : Engine.o

# target to build an object file
Engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfmlapp.dir/build.make CMakeFiles/sfmlapp.dir/Engine.cpp.o
.PHONY : Engine.cpp.o

Engine.i: Engine.cpp.i
.PHONY : Engine.i

# target to preprocess a source file
Engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfmlapp.dir/build.make CMakeFiles/sfmlapp.dir/Engine.cpp.i
.PHONY : Engine.cpp.i

Engine.s: Engine.cpp.s
.PHONY : Engine.s

# target to generate assembly for a file
Engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfmlapp.dir/build.make CMakeFiles/sfmlapp.dir/Engine.cpp.s
.PHONY : Engine.cpp.s

GameMenu.o: GameMenu.cpp.o
.PHONY : GameMenu.o

# target to build an object file
GameMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfmlapp.dir/build.make CMakeFiles/sfmlapp.dir/GameMenu.cpp.o
.PHONY : GameMenu.cpp.o

GameMenu.i: GameMenu.cpp.i
.PHONY : GameMenu.i

# target to preprocess a source file
GameMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfmlapp.dir/build.make CMakeFiles/sfmlapp.dir/GameMenu.cpp.i
.PHONY : GameMenu.cpp.i

GameMenu.s: GameMenu.cpp.s
.PHONY : GameMenu.s

# target to generate assembly for a file
GameMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfmlapp.dir/build.make CMakeFiles/sfmlapp.dir/GameMenu.cpp.s
.PHONY : GameMenu.cpp.s

Players.o: Players.cpp.o
.PHONY : Players.o

# target to build an object file
Players.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfmlapp.dir/build.make CMakeFiles/sfmlapp.dir/Players.cpp.o
.PHONY : Players.cpp.o

Players.i: Players.cpp.i
.PHONY : Players.i

# target to preprocess a source file
Players.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfmlapp.dir/build.make CMakeFiles/sfmlapp.dir/Players.cpp.i
.PHONY : Players.cpp.i

Players.s: Players.cpp.s
.PHONY : Players.s

# target to generate assembly for a file
Players.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfmlapp.dir/build.make CMakeFiles/sfmlapp.dir/Players.cpp.s
.PHONY : Players.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfmlapp.dir/build.make CMakeFiles/sfmlapp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfmlapp.dir/build.make CMakeFiles/sfmlapp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfmlapp.dir/build.make CMakeFiles/sfmlapp.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sfmlapp"
	@echo "... Engine.o"
	@echo "... Engine.i"
	@echo "... Engine.s"
	@echo "... GameMenu.o"
	@echo "... GameMenu.i"
	@echo "... GameMenu.s"
	@echo "... Players.o"
	@echo "... Players.i"
	@echo "... Players.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

